### ISSUE TITLE
Radar_pa_node.py Data.ID = 607

### ISSUE THREAD

**Issue by Franzisdrak** [TUC-ProAut/ros_radar#1]
Hey there,

i am having an issue understand the following line in radar_pa_node.py 
if (data.id == 607):

I dont't find anything in the spec about this and would like to know what it does exactly, as i can't seem to ever have msg_A and msg_B have the same counter.

Kind regards
Franz

**Comment by khagag14** [comment]
Hi, 
as you can see in the spec (page 34) range of the msg ID starts from 0x200(msgA) to 0x25F(607)(msgB).
so one of the checkschecks is; the last ID 607 before publish. 

Br
Karim Haggag
